import Head from 'next/head'
import {FC} from "react";
import CategoryNav from "@/components/CategoryNav";
import {API_URL} from "@/core/constants";
import {IHomePageProps, IPostData} from "@/core/types";
import Link from "next/link";

const Home:FC<IHomePageProps> = ({categories, posts}) => {

    const addPostHref = (post: IPostData) => {
        if (!post.category.editable) {
            return `${post.category.titleUrl}/${post.creator?.nickName}/posts/${post.titleUrl}`
        }
        return `${post.category.titleUrl}/posts/${post.titleUrl}`
    }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <div style={{minHeight:'1000px'}}>
              <CategoryNav categories={categories}/>
              {
                posts?.map((post) => {
                    return(
                        <>
                            <div>
                                <Link href={addPostHref(post)}>
                                    {post.title}
                                </Link>
                                <div>
                                    {post.viewsCount}
                                    {post.category.title}
                                </div>
                            </div>


                        </>
                    )
                })
              }
          </div>
      </main>
    </>
  )
}

export default Home;

export async function getServerSideProps() {
    const categories = await fetch(`${API_URL}/blog/category/`).then(r => r.json())
    const posts = await fetch(`${API_URL}/posts/`).then(r => r.json())

    return {
        props: {categories: categories, posts: posts}
    }
}
